<a href="https://colab.research.google.com/github/Isfhan/machine-learning-opencv/blob/master/dealing_data_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Dealing with data using Python's NumPy package

In [1]:
#importing Numpy
import numpy as np

In [2]:
#Checking Version
np.__version__

'1.18.5'

##Understanding NumPy arrays

In [3]:
# Creating a list in Python
init_list = list(range(10))
init_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
# Converting list in Numpy array 
init_array = np.array(init_list)
init_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Lets see what happen when we try to multiply every element in the array 
init_array * 2
# The same works with addition, subtraction, division, and many other functions.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
# Every NumPy array comes with the following attributes:
# ndim: The number of dimensions
# shape: The size of each dimension
# size: The total number of elements in the array
# dtype: The data type of the array (for example, int, float, string, and so on)



print("init_array ndim: The number of dimensions",init_array.ndim)
print("init_array The size of each dimension", init_array.shape)
print("init_array size: The total number of elements in the array", init_array.size)
print("init_array dtype: The data type of the array",init_array.dtype)




init_array ndim: The number of dimensions 1
init_array The size of each dimension (10,)
init_array size: The total number of elements in the array 10
init_array dtype: The data type of the array int64


In [7]:
# Accessing 1D array elements by indexing
init_array[0]

0

In [8]:
init_array[3]

3

In [9]:
init_array[-1]


9

In [10]:
init_array[-2]

8

In [11]:
# Slicing Array
# from index 2 up to index 5 - 1
init_array[2:5]

array([2, 3, 4])

In [12]:
# from the beginning up to index 5 - 1
init_array[:5]

array([0, 1, 2, 3, 4])

In [13]:
# from index 5 up to the end of the array
init_array[5:]

array([5, 6, 7, 8, 9])

In [14]:
# every other element
init_array[::2]

array([0, 2, 4, 6, 8])

In [15]:
# the entire array in reverse order
init_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])